---
title: "16p HiC - Compartment Analysis"
author: "Siddharth Reed"
date: "`r Sys.Date()`"
---
<style type="text/css">
.main-container {
  max-width: 1800px !important;
  margin-left: auto;
  margin-right: auto;
}
</style>

# Dependencies + Load data

```{r knitr}
library(knitr)
knitr::opts_chunk$set(
    results=FALSE,
    message=FALSE,
    warning=FALSE,
    dev=c('png', 'pdf', 'svg'),
    dpi=300
)
```
Set up file locations + load dependences
```{r dependencies}
library(here)
here::i_am('notebooks/Compartments.Rmd')
BASE_DIR <- here()
source(file.path(BASE_DIR, 'scripts/locations.R'))
source(file.path(SCRIPT_DIR, 'utils.data.R'))
source(file.path(BASE_DIR, 'scripts/constants.R'))
source(file.path(SCRIPT_DIR, 'utils.plot.R'))
source(file.path(SCRIPT_DIR, 'utils.annotations.R'))
source(file.path(SCRIPT_DIR, 'loops/utils.compartments.R'))
library(tidyverse)
library(magrittr)
```
Load all cooltools eigen decomposition data
```{r load_eigs}
# this is applied to the donut kernel, but all loops are significant with
comparments.df <- 
    check_cached_results(
        results_file=ALL_COMPARTMENTS_RESULTS_FILE,
        # force_redo=TRUE,
        results_fnc=load_all_cooltools_compartment_results,
    ) %>%
    post_process_cooltools_compartment_results() %>% 
    standardize_data_cols()
```


