---
title: "HiCRep analysis of 16p samples"
author: "Siddharth Reed"
date: "`r Sys.Date()`"
output: 
    html_document:
        toc: true
        toc_float: true
        theme: paper
        code_folding: hide
        df_print: paged
---

# Prepare data

Set up file locations
```{r}
library(here)
BASE_DIR=here()
source(file.path(BASE_DIR, 'scripts/locations.R'))
```
Load dependencies
```{r}
library(tidyverse)
library(magrittr)
source(file.path(BASE_DIR, 'scripts/utils.data.R'))
source(file.path(BASE_DIR, 'scripts/utils.hicrep.R'))
```
Load hicrep data
```{r results='hide'}
hicrep.results <- 
    check_cached_results( 
        HICREP_RESULTS_FILE,
        force_redo=FALSE,
        return_data=TRUE,
        results_fnc=load_all_hicrep_results
    )
```

Print sample rows
```{r rows.print=5}
hicrep.results %>% 
    arrange(resolution, h, is.downsampled, window.size, chr, SampleNumber)
```

# Summary Stats

How many different parameter combinations we tried
```{r rows.print=5}
hicrep.results %>%
    filter(chr == 'chr16') %>% 
    dplyr::count(!!!syms(HICREP_PARAM_NAMES))
```

How many different pairs of sample matrices were compared
```{r rows.print=5}
hicrep.results %>%
    filter(chr == 'chr16') %>% 
    dplyr::count(
        Edit,
        Genotype,
        Celltype,
        SampleNumber,
        ReadFilter
    )
```

# Plot distributions of HiCRep scores 

```{r include=FALSE}
plot.df <- 
    hicrep.results %>%
    mutate(resolution=as.integer(resolution)) %>% 
    left_join(
        RESOLUTION_NAMES,
        by=join_by(resolution == Resolution)
    ) %>%
    select(-c(resolution)) %>% 
    rename(resolution=Resolution.name)
```

Boxplot of hicrep scores by various levels
