---
title: "Matrix Coverage for 16p HiC samples"
author: "Siddharth Reed"
date: "`r Sys.Date()`"
---

<style type="text/css">
.main-container {
  <!-- max-width: 1800px !important; -->
  margin-left: auto;
  margin-right: auto;
}
</style>

# Dependencies + Load data

```{r knitr}
library(knitr)
knitr::opts_chunk$set(
    # eval=FALSE,
    results=FALSE,
    message=FALSE,
    warning=FALSE,
    dev=c('png', 'pdf', 'svg'),
    # dev=c('pdf'),
    dpi=300
)
```
Set up file locations + load dependencies
```{r dependencies, eval=TRUE}
library(here)
here::i_am('notebooks/matrix.coverage.Rmd')
BASE_DIR <- here()
source(file.path(BASE_DIR, 'scripts', 'locations.R'))
source(file.path(SCRIPT_DIR, 'utils.data.R'))
source(file.path(BASE_DIR, 'scripts', 'constants.R'))
source(file.path(SCRIPT_DIR, 'utils.annotations.R'))
source(file.path(SCRIPT_DIR, 'utils.plot.R'))
source(file.path(SCRIPT_DIR, 'coverage', 'utils.coverage.R'))
library(magrittr)
library(tidyverse)
```
Load marginal coverage
```{r load_marginal_coverage_summary_stats}
coverage.summary <- 
    check_cached_results(
        results_file=RESOLTION_COVERAGE_SUMAMRY_FILE,
        # force_redo=TRUE,
        results_fnc=compute_all_coverage_summaries,
        resolutions=c(100, 50, 25, 10) * 1e3   # Kbs
    ) %>%
    post_process_coverage_summaries(load_sample_metadata(filter=FALSE)) %>% 
    standardize_data_cols()
```

# Marginal Coverage Summary Stats {.tabset}

## Genome Wide {.tabset}

```{r total_heatmaps_gw, results='asis', fig.dim=c(12,7)}
coverage.summary %>% 
    filter(isGenome == 'Genome.Wide') %>% 
    filter(
        metric %in% c(
            # 'bins.n.total',
            # 'bins.n.detected',
            # 'bins.n.nz',
            'bins.n.covered',
            # 'bins.pct.nz',
            # 'bins.pct.covered',
            # 'coverage.min',
            # 'coverage.q25',
            'coverage.median',
            'coverage.mean',
            # 'coverage.q75',
            # 'coverage.max',
            'coverage.total'
        )
    ) %>% 
    mutate(
        labels=
            case_when(
                grepl('.pct.', metric) ~ scales::number(value, accuracy=0.01, stype_positive='none'),
                TRUE                   ~ scales::number(value, accuracy=0.1,  stype_positive='none', scale_cut=cut_short_scale())
            )
    ) %>% 
    make_nested_plot_tabs(
        group.cols=c('isMerged', 'weight', 'resolution'),
        max.header.lvl=3,
        plot.fnc=plot_barplot,
        x.var='SampleID',
        x.scale.mode='discrete',
        y.var='value',
        y.scale.mode='m',
        fill.var='Genotype', 
        facet.col='Celltype',
        facet.row='metric',
        scales='free',
        legend.position='right',
        axis.title.y=element_blank(),
        axis.title.x=element_blank(),
        axis.text.x=element_text(angle=45, hjust=1)
    )
```

## Per Chr {.tabset}

```{r total_heatmaps_chr, results='asis', fig.dim=c(15,8)}
coverage.summary %>% 
    filter(isGenome != 'Genome.Wide') %>% 
    filter(
        metric %in% c(
            # 'bins.n.total',
            # 'bins.n.detected',
            # 'bins.n.nz',
            # 'bins.n.covered',
            'bins.pct.nz',
            'bins.pct.covered',
            # 'coverage.min',
            # 'coverage.q25',
            'coverage.median',
            'coverage.mean',
            # 'coverage.q75',
            # 'coverage.max',
            'coverage.total'
        )
    ) %>% 
    mutate(
        labels=
            case_when(
                grepl('.pct.', metric) ~ scales::number(value, accuracy=0.01, stype_positive='none'),
                TRUE                   ~ scales::number(value, accuracy=0.1,  stype_positive='none', scale_cut=cut_short_scale())
            )
    ) %>% 
    make_nested_plot_tabs(
        group.cols=c('isMerged', 'weight', 'metric', 'resolution'),
        max.header.lvl=3,
        plot.fnc=plot_heatmap,
        x.var='chr',
        y.var='SampleID',
        fill.var='value', 
        facet.row='Celltype',
        scales='free',
        label.var='labels',
        label.size=2.75,
        label.color='white',
        legend.position='top',
        legend.text=element_text(angle=45, hjust=1),
        axis.text.x=element_text(angle=45, hjust=1),
        element.title=element_blank(),
        plot.elements=
            list(
                scale_fill_continuous(
                    labels=scales::label_number(scale_cut=scales::cut_short_scale())
                )
            )
    )
```

