---
title: "16p Region Investigation"
author: "Siddharth Reed"
date: "`r Sys.Date()`"
---
<style type="text/css">
.main-container {
  max-width: 1800px !important;
  margin-left: auto;
  margin-right: auto;
}
</style>

# Set up + Load all differential contact results

```{r knitr}
library(knitr)
knitr::opts_chunk$set(
    eval=TRUE,
    warning=FALSE,
    message=FALSE,
    results=FALSE,
    dev=c('png', 'pdf', 'svg'),
    dpi=300
)
```
Set up file locations + load dependenies
```{r dependencies}
library(here)
here::i_am('notebooks/plot.contacts.Rmd')
BASE_DIR <- here()
library(GenomicRanges)
library(InteractionSet)
library(gghic)
library(patchwork)
source(file.path(BASE_DIR, 'scripts', 'locations.R'))
source(file.path(SCRIPT_DIR, 'utils.data.R'))
source(file.path(BASE_DIR, 'scripts', 'constants.R'))
source(file.path(SCRIPT_DIR, 'utils.plot.R'))
source(file.path(SCRIPT_DIR, 'TADs',  'utils.TADs.R'))
source(file.path(SCRIPT_DIR, 'loops', 'utils.loops.R'))
library(magrittr)
library(tidyverse)
```
List regions to plot
```{r specify_regions_to_plot}
regions.df <- 
    GENOMIC_REGIONS %>%
    filter(region.dist < 6e7, region.chr == 'chr16') %>% 
    head(4) %>% 
    select(region, region.chr, region.UCSC) %>%
    rename(
        'chr'=region.chr,
        'focus'=region.UCSC,
        'region.title'=region
    )
```
Load annotation data
```{r plot_hyper_params}
hyper.params.df <- 
    expand_grid(
        resolution=c(50, 25, 10) * 1e3,
        weight=c('balanced', 'raw')
    )
```
Load annotation data
```{r load_annotation_data}
tads.df   <- load_TADs_for_gghic()
loops.df  <- load_loops_for_gghic()
tracks.df <- NULL
# tracks.df <- 
#     check_cached_results(
#         results_file=GGHIC_TRACK_DATA,
#         # force_redo=TRUE,
#         results_fnc=load_tracks_for_gghic,
#         resolutions=resolutions
#     )
```
Set up plot params 
```{r set_up_plot_params}
params.df <-
    set_up_gghic_plot_param_sets(
        regions.df=regions.df,
        hyper.params.df=hyper.params.df,
        tads.df=tads.df,
        loops.df=loops.df,
        tracks.df=tracks.df
    )
```

# Heatmap + Feature Annotations

Plot all regions
```{r generate_plots, results='asis', fig.dim=c(8, 12)}
PLOT_DIR <- file.path(RESULTS_DIR, 'gghic.plots')
params.df %>% 
    filter(resolution %in% c('10Kb', '25Kb')) %>% 
    # filter(resolution %in% c('10Kb')) %>% 
    filter(weight == 'balanced') %>% 
    filter(Celltype == 'NSC') %>% 
    # gghic specific params
    add_column(
        # gtf_path=GENOME_GTF_FILE,
        length_ratio=1,
        # ideogram_width_ratio=1/30,
        # ideogram_fontsize=10,
        # ideogram_colour="red",
        # ideogram_fill="#FFE3E680",
        annotation_style="arrow",
        max_gaps=1e6,
        # annotation_width_ratio=1/50,
        # annotation_spacing_ratio=1/3,
        annotation_fontsize=10,
        annotation_colour="#48CFCB",
        annotation_fill="#48CFCB",
        include_ncrna=FALSE,
        # track_width_ratio=1/20,
        # track_spacing_ratio=1/2,
        # track_fill="black",
        # track_fontsize=5,
        tad_colour="#00ff83",
        loop_style="arc",
        stroke=1,
        # loop_colour="black",
        # loop_fill=NA,
        # expand_xaxis=FALSE,
        # expand_left=NULL,
        # expand_right=NULL,
    ) %>% 
    # generated pdfs for each plot
    pmap(
        .l=., 
        .f=check_cached_results,
        # force_redo=TRUE,
        results_fnc=plot_all_regions_gghic,
        .progress=TRUE
    )
```

# Cached

Plot all regions
```{r plot_chr16_caches, fig.dim=c(10, 6), eval=FALSE}
mutate(region.title=glue('{SampleID}@{resolution} in {region.title} ({focus})'))
    # make_nested_plot_tabs(
    #     group.cols=c('weight', 'resolution', 'focus'),
    #     max.header.lvl=2,
    #     plot.fnc=plot_all_regions_gghic
    # )
```

