---
title: "QC stats for 16p HiC samples"
author: "Siddharth Reed"
date: "`r Sys.Date()`"
output: 
    html_document:
        toc: true
        toc_float: true
        theme: paper
        code_folding: hide
        df_print: paged
---
<style type="text/css">
.main-container {
  max-width: 1800px !important;
  margin-left: auto;
  margin-right: auto;
}
</style>

# Prepare data

Set up file locations
```{r results=FALSE}
library(here)
BASE_DIR=here()
source(file.path(BASE_DIR, 'scripts/locations.R'))
```
Load dependencies
```{r}
library(tidyverse)
library(magrittr)
source(file.path(BASE_DIR, 'scripts/utils.data.R'))
source(file.path(BASE_DIR, 'scripts/utils.qc.R'))
source(file.path(BASE_DIR, 'scripts/utils.plot.R'))
```
Load sample metadata
```{r message=FALSE, rows.print=5}
sample.metadata <- load_sample_metadata()
sample.metadata
```
Load contact matrices for each file
```{r load_contacts, rows.print=5}
contacts.df <- 
    load_mcool_files(
        pattern='*.NSC.*.mapq_30.1000.mcool',
        range1s='chr16',
        resolutions=c(RESOLUTION),
    ) %>%
    left_join(
        sample.metadata,
        by='Sample.ID'
    ) %>%
    mutate(Sequencing.Run=ifelse(is.na(Sequencing.Run), 'Merged', Sequencing.Run))
contacts.df
```
Prepare data for plotting
```{r}
plot.df <- 
    check_cached_results(
        results_file=ROBINSON_REPLICATION_DATA_FILE,
        force_redo=FALSE,
        return_data=TRUE,
        show_col_types=FALSE,
        results_fnc=annotate_contact_regions,
        contacts.df=contacts.df,
        regions.of.interest=
            GENOMIC_REGIONS %>%
            filter(
                region %in% c(
                    "chr16p.deletion",
                    "chr16p.telomere",
                    "chr16p",
                    "chr16q"
                )
            ),
        most_specific_only=TRUE
    ) %>%
    select(
        -c(
            ReadFilter,
            resolution,
            weight
        )
    )
plot.df %>% dplyr::count(Sample.ID, region)
```


# Plot IFs of ELISE vs CTRL regions 

```{r}
plot.df %>%
    filter(region != '16.all.Distance.Matched.Control') %>%
    # filter(count < 200) %>% 
    nest(interactions=-c(normalization, min_count, plot_file)) %>%
    rowwise() %>%
    mutate(
        height=10,
        width=10,
        independent='y',
        scales='free_y',
        p_size=2.5,
        n_size=2.75,
        n_pos=ifelse(normalization == 'NONE', 0, 3e-4),
        test_offset_y=
            case_when(
                normalization == 'cis.ice' ~ 5e-4,
                normalization == 'NONE' ~ 2,
                normalization == 'cis.vc' ~ 10,
            ),
        expansion=
            ifelse(
                normalization == 'NONE',
                list(c(4e-2, 1e-2, 10e-2, 1e-2 )), 
                list(c(5e-3, 1e-4,  5e-2, 1e-4))
            )
    ) %>% 
    pmap(
        .l=.,
        .f=plot_wrapper,
    )
```

```{r} 
plot.df %>% 
    filter(Replicate.ID == 'Merged') %>% 
    filter(normalization == 'NONE') %>% 
    filter(min_count == 1) %>% 
    filter(region %in% c('16p11.2 CNV - Telomere', '16p.Distance.Matched.Control')) %>%
    plot_elise_boxplot(
        independent='y',
        scales='free_y',
        y_val='count',
        p_size=2.5, n_size=2.75, test_offset_y=5, expansion=1e-2 * c(3, 1, 5, 1)
    ) %>%
    ggsave(
        glue('{PLOT_DIR}/presentation.boxplot.pdf'),
        .,
        width=10,
        height=6,
        units='in'
    )
```
