---
title: "TADCompare Analysis for 16p"
author: "Siddharth Reed"
date: "`r Sys.Date()`"
---
<style type="text/css">
.main-container {
  max-width: 1800px !important;
  margin-left: auto;
  margin-right: auto;
}
</style>

# Set Up

```{r knitr}
library(knitr)
knitr::opts_chunk$set( 
    results=FALSE,
    message=FALSE,
    warning=FALSE,
    dev=c('png', 'pdf', 'svg'),
    dpi=300
)
```
Set up file locations + load dependences
```{r dependencies}
library(here)
here::i_am('notebooks/TADCompare.Rmd')
BASE_DIR <- here()
source(file.path(BASE_DIR, 'scripts', 'locations.R'))
source(file.path(SCRIPT_DIR, 'utils.data.R'))
source(file.path(BASE_DIR, 'scripts', 'constants.R'))
source(file.path(SCRIPT_DIR, 'utils.plot.R'))
source(file.path(SCRIPT_DIR, 'TADs', 'utils.TADs.R'))
source(file.path(SCRIPT_DIR, 'TADs', 'utils.TADCompare.R'))
library(tidyverse)
library(magrittr)
```
Load TADCompare results
```{r load_TADCompare_data}
all.TADCompare.results.df <- 
    check_cached_results(
        results_file=TADCOMPARE_RESULTS_FILE,
        # force_redo=TRUE,
        results_fnc=load_all_TADCompare_results
    ) %>%
    post_process_TADCompare_results() %>% 
    standardize_data_cols()
```
Print summary of results
```{r print_summaries, eval=FALSE}
# all.TADCompare.results.df %>% head(2) %>% t()
all.TADCompare.results.df %>%
    dplyr::count(
        resolution, 
        #z.thresh, window.size, gap.thresh,
        TAD.method, TAD.params, 
        comparison, 
        isBoundary, isDifferential
    )
all.TADCompare.results.df %>%
    filter(isBoundary) %>% 
    # filter(TAD.isDifferential) %>% 
    dplyr::count(
        resolution, 
        #z.thresh, window.size, gap.thresh,
        TAD.method, TAD.params, 
        comparison, 
        Enriched.Condition, 
        isBoundary, isDifferential, Difference
    ) %>%
    select(-c(TAD.params, isBoundary)) %>%
    pivot_wider(
        names_from=TAD.method,
        values_from=n
    ) %>% 
    # select(-c(comparison, TAD.params, isBoundary)) %>%
    print(n=Inf)
```

# Plot TAD differences {.tabset}

```{r plot_n_diffs}
n.compare.df <- 
    all.TADCompare.results.df %>% 
    dplyr::count(
        resolution, 
        #z.thresh, window.size, gap.thresh,
        TAD.method, TAD.params, 
        comparison, 
        Enriched.Condition, 
        isBoundary, isDifferential, Difference,
        name='n.diffs'
    )
```
Plot heatmap
```{r n_loops_heatmap_binary}
all.TADCompare.results.df %>% 
    dplyr::count(
        resolution, 
        #z.thresh, window.size, gap.thresh,
        TAD.method, TAD.params, 
        comparison, 
        Enriched.Condition, 
        isBoundary, isDifferential,
        name='n.diffs'
    ) %>% 
    # filter(isBoundary, isDifferential) %>% 
    filter(isBoundary) %>% 
    make_nested_plot_tabs(
        # group.cols=c('TAD.params', 'resolution'),
        group.cols=c('resolution'),
        plot.fnc=plot_barplot,
        max.header.lvl=2,
        x.scale.mode='discrete',
        x.var='comparison',
        y.var='n.diffs',
        # fill.var='isDifferential',
        # facet.row='TAD.method',
        fill.var='TAD.method',
        facet.row='isDifferential',
        # label.var='n.diffs',
        # legend.position='top',
        axis.text.x=element_text(angle=45, hjust=1),
        # legend.text=element_text(angle=35, hjust=1),
        axis.title.x=element_blank(),
        axis.title.y=element_blank()
    )
```
Plot heatmap
```{r n_loops_heatmap}
n.compare.df %>% 
    filter(isBoundary, isDifferential) %>% 
    # filter(isBoundary) %>% 
    make_nested_plot_tabs(
        # group.cols=c('TAD.params', 'resolution'),
        group.cols=c('resolution'),
        plot.fnc=plot_heatmap,
        max.header.lvl=3,
        y.var='comparison',
        x.var='Difference',
        fill.var='n.diffs', 
        label.var='n.diffs',
        facet.row='TAD.method',
        # legend.position='top',
        # axis.text.x=element_text(angle=45, hjust=1),
        # legend.text=element_text(angle=35, hjust=1),
        axis.title.x=element_blank(),
        axis.title.y=element_blank()
    )
```

