---
title: "TAD Analysis"
author: "Siddharth Reed"
date: "`r Sys.Date()`"
output: 
    html_document:
        keep_md: yes
        toc: true
        toc_float: true
        theme: paper
        code_folding: hide
        df_print: paged
---
<style type="text/css">
.main-container {
  max-width: 1800px !important;
  margin-left: auto;
  margin-right: auto;
}
</style>

# Prepare data

```{r knitr}
library(knitr)
knitr::opts_chunk$set(
    dev=c('png', 'pdf', 'tiff'),
    dpi=300
)
```
Set up file locations
```{r locations, results=FALSE}
library(here)
BASE_DIR=here()
source(file.path(BASE_DIR, 'scripts/locations.R'))
```
Load dependencies
```{r deps}
library(tidyverse)
library(magrittr)
source(file.path(BASE_DIR, 'scripts/utils.data.R'))
source(file.path(BASE_DIR, 'scripts/utils.plot.R'))
source(file.path(BASE_DIR, 'scripts/utils.TADs.R'))
```
Load sample metadata
```{r load_metadata, message=FALSE, rows.print=5}
sample.metadata <- load_sample_metadata()
sample.metadata
```

# Load Directionality Index scores

```{r load_DI}
DI.scores <- 
    load_all_TAD_annotations(
        tad_annotations_dir=glue('{BASE_DIR}/results/TADs/hiTAD'),
        tad.method='hiTAD-DIs',
        file_suffix='-DIs.txt',
        param_names=
            c(
                'Normalization',
                'Resolution',
                'SampleName'
            ),
    ) %>%
    separate_wider_delim(
        SampleName,
        delim=fixed('.'),
        names=
            c(
                'SampleName',
                NA,
                'ReadFilter',
                NA
            )
    ) %>% 
    mutate(
        Resolution=as.integer(Resolution),
        chr=factor(chr, levels=CHROMOSOMES)
    ) 
DI.scores %>% head(2) %>% t()
```

# Load all TAD annotations

Load all TAD Annotations
```{r load_TADs}
tad.annotations <- load_all_TAD_annotations()
tad.annotations <- 
    load_all_TAD_annotations() %>% 
    mutate(
        resolution=as.integer(resolution),
        chr=factor(chr, levels=CHROMOSOMES)
    ) 
    # Get chromosome size in bins per resolution for convienience
    # left_join(
    #     DI.scores %>%
    #     select(-c(DI, Method)) %>%
    #     group_by(across(-starts_with('bin.'))) %>%
    #     dplyr::count(name='chrom.total.bins')
    # )
tad.annotations %>% head(2) %>% t()
tad.annotations %>% dplyr::count(Method, Normalization, ReadFilter, Resolution, SampleName, Genotype) %>% print(n=Inf)
```

# Plot number of TADs across samples

```{r plot_TAD_n}
tad.annotations %>%
    dplyr::count(Resolution, Genotype, SampleName, chr) %>%
    group_by(Resolution) %>%
    group_map(
        ~ ggplot(
            .x, 
            aes(
                x=chr,
                y=SampleName,
                fill=n
            )
        ) +
        geom_tile() +
        scale_fill_viridis(discrete=FALSE) +
        labs(title=sprintf('16p sample TADs @ %sKb', .x$Resolution / 1000)) +
        theme(
            axis.title.x=element_blank(),
            axis.title.y=element_blank(),
            axis.text.x=element_text(angle=45, hjust=1),
            axis.text.y=element_markdown()
        ) +
        add_ggtheme(),
        .keep=TRUE
    ) %>% 
    cowplot::plot_grid(
        plotlist=.,
        align='v',
        ncol=2
    )
```

# Plot TAD length Distribution

```{r plot_TAD_length}
tad.annotations %>%
    filter(chr %in% paste0('chr', c(1,3,5,10,16,20,'X'))) %>% 
    mutate(TAD.length=(TAD.end - TAD.start) / Resolution) %>% 
    mutate(Resolution=glue('{Resolution / 1000}Kb')) %>% 
    mutate(Resolution=factor(Resolution, levels=c('100Kb', '50Kb', '10Kb', '5Kb'))) %>% 
    group_by(Method) %>%
    group_map(
        ~ ggplot(
            .x, 
            aes(
                y=TAD.length,
                x=Genotype,
                color=Replicate,
            )
        ) +
        geom_boxplot() +
        labs(x='TAD Length (bins)') +
        ggh4x::facet_grid2(cols=vars(chr), rows=vars(Resolution), scales='free_y') + #, independent='y') +
        theme(
            axis.title.x=element_blank(),
            axis.text.x=element_text(angle=45, hjust=1),
            axis.text.y=element_markdown()
        ) +
        add_ggtheme(),
        .keep=TRUE
    ) %>% 
    cowplot::plot_grid(
        plotlist=.,
        align='v',
        ncol=1
    )
```

# Plot DI Scores

```{r plot_DI}
tmp <- 
    DI.scores %>%
    add_count(Resolution, SampleName, chr, name='n.bins') %>% 
    left_join(
        tad.annotations %>% select(c(Resolution, SampleName, chr, TAD.start, TAD.end)),
        by=
            join_by(
                Resolution,
                chr,
                SampleName,
                between(bin.start, TAD.start, TAD.end, bounds='[)')
            ) 
    ) %>%
    mutate(
        TAD.boundaries=
            case_when(
                bin.start == TAD.start ~ 'TAD.Start',
                bin.end == TAD.end ~ 'TAD.End',
                bin.start >= TAD.start & bin.end <= TAD.end ~ 'TAD.inner',
                TRUE ~ 'Non-TAD'
        )
    )
tmp %>% 
    # filter(chr %in% paste0('chr', c(1,3,5,10,16,20,'X'))) %>% 
    filter(chr == 'chr16') %>% 
    mutate(Resolution=glue('{Resolution / 1000}Kb')) %>%
    mutate(Resolution=factor(Resolution, levels=c('100Kb', '50Kb', '10Kb', '5Kb'))) %>% 
    group_by(Method) %>%
    group_map(
        ~ ggplot(
            .x, 
            aes(
                x=bin.start,
                y=DI,
                group=chr,
                color=Genotype
                # color=Genotype, shape=Replicate
            )
        ) +
        # geom_rect(data=.x %>% filter(SampleName == ''), aes(xmin=TAD.start, xmax=TAD.end, ymin=-Inf, ymax=0, fill=SampleName), alpha=0.01, size=0) +
        geom_line() +
        labs(x='bins', y='Directionality Index') +
        ggh4x::facet_grid2(cols=vars(chr), rows=vars(Resolution), scales='free_y') +
        scale_x_continuous(
            n.breaks=10,
            expand=c(0.01, 0.01, 0.01, 0.01),
            limits=c(0, NA)
        ) +
        theme(
            legend.position='top',
            axis.title.x=element_blank(),
            axis.text.x=element_text(angle=45, hjust=1),
            axis.text.y=element_markdown()
        ) +
        add_ggtheme(),
        .keep=TRUE
    ) %>% 
    cowplot::plot_grid(
        plotlist=.,
        align='v',
        ncol=1
    )
```
