library(tidyverse)
library(glue)
library(purrr)
###############
# Load various QC data files/sets of files
load_pairtools_stats <- function(
    stats_file_suffix='.HiC.hg38.dedup.stats',
    ...){
    # Load all stats
    all.stats.df <- 
        PAIRS_DIR %>%
        list.files(
            full.names=FALSE,
            recursive=TRUE,
            pattern=glue('*{stats_file_suffix}$')
        ) %>%
        tibble(fileinfo=.) %>% 
        mutate(filepath=file.path(PAIRS_DIR, fileinfo)) %>% 
        mutate(Sample.ID=str_remove(basename(fileinfo), stats_file_suffix)) %>% 
        select(-c(fileinfo)) %>% 
        mutate(
            stats=
                purrr::pmap(
                    .l=.,
                    function(filepath, ...){
                        filepath %>% 
                        read_tsv(
                            show_col_types=FALSE,
                            col_names=c('stat', 'value')
                        )
                    }
                )
        ) %>%
        select(-c(filepath)) %>%
        unnest(stats)
    all.stats.df <- 
        all.stats.df %>% 
        separate_wider_delim(
            Sample.ID,
            delim=fixed('.'),
            names=c('Edit', 'Genotype', 'SampleNumber', 'Celltype'),
            cols_remove=FALSE
        ) %>% 
        group_by(Edit, Genotype, Celltype, stat) %>%
        summarize(value=sum(value)) %>%
        ungroup() %>% 
        mutate(Sample.ID=glue('{Edit}.{Genotype}.Merged.{Celltype}')) %>%
        select(-c(Edit, Genotype, Celltype)) %>% 
        bind_rows(all.stats.df)
    # Get total number of contacts per sample
    total.contacts.df <- 
        all.stats.df %>% 
        filter(!grepl('/', stat)) %>%
        filter(stat == 'total_nodups') %>% 
        select(Sample.ID, value) %>%
        dplyr::rename('total.unique.contacts'=value)
    # Matrix-wide stats
    general.stats.df <- 
        all.stats.df %>% 
        filter(!grepl('/', stat)) %>%
        mutate(
            category=
                case_when(
                    grepl('total', stat) ~ 'Reads', 
                    TRUE ~ 'Contacts'
                )
        ) %>% 
        left_join(
            total.contacts.df,
            by='Sample.ID'
        )
    # stats about contact distances
    dist.stats.df <- 
        all.stats.df %>% 
        filter(grepl('^dist_freq', stat)) %>%
        separate_wider_delim(
            stat,
            delim='/',
            names=
                c(
                    'interaction',
                    'range',
                    'orientation'
                )
        ) %>%
        mutate(range=str_remove(range, fixed('+'))) %>% 
        separate_wider_delim(
            range,
            delim='-',
            names=c('range.start', 'range.end'),
            too_few='align_start'
        ) %>%
        mutate(across(starts_with('range'), ~ as.integer(.x))) %>% 
        mutate(interaction='cis') %>%
        left_join(total.contacts.df, by='Sample.ID')
    # Contact Frequency Stats per Chromosome
    chr.stats.df <- 
        all.stats.df %>% 
        filter(grepl('^chrom_freq', stat)) %>%
        separate_wider_delim(
            stat,
            delim='/',
            names=
                c(
                    'stat',
                    'chr1',
                    'chr2'
                )
        ) %>% 
        left_join(total.contacts.df, by='Sample.ID')
    # Return named list of all stuff
    return(
        list(
            'general.stats'=general.stats.df,
            'distance.stats'=dist.stats.df,
            'chr.stats'=chr.stats.df
        )
    )
}

load_genome_coverage <- function(
    delim='-',
    weights=NULL,
    resolutions=NULL){
    # input_dir=COVERAGE_DIR; suffix='coverage.tsv'; param_names=c('weight', 'resolution'); delim='-'; resolutions=c(1000, 100000); weights=c('raw')
    # List input files (generated by cooltools coverage)
    parse_results_filelist(
        input_dir=COVERAGE_DIR,
        suffix='-coverage.tsv',
        filename.column.name='matrix.name',
        param_delim='_',
    ) %>%
    process_matrix_name() %>% 
    # Ignore results not matching param values
    { 
        if (is.null(resolutions)) { 
            . 
        } else { 
            filter(., resolution %in% resolutions) 
        } 
    } %>%
    { 
        if (is.null(weights)) { 
            . 
        } else { 
            filter(., weight %in% weights) 
        } 
    } %>%
    mutate(
        coverage=
            purrr::pmap(
                .l=.,
                .f=function(filepath, ...){
                    read_tsv(
                        filepath,
                        show_col_types=FALSE,
                        progress=FALSE
                    )
                }
            )
    ) %>%
    unnest(coverage) %>%
    rename_with(~ str_remove(.x, '_(raw|weight)')) %>% 
    rename(
        'chr'=chrom,
        'coverage.cis'=cov_cis,
        'coverage.total'=cov_tot,
    ) %>% 
    mutate(chr=factor(chr, levels=CHROMOSOMES)) %>%  
    pivot_longer(
        starts_with('coverage'),
        names_to='metric',
        names_prefix='coverage.',
        values_to='coverage'
    )
}

make_summary_stats_table <- function(
    coverage.summary,
    pair.stats.list,
    pair.plot.df,
    ...){
# Start with coverage data
    coverage.summary %>%
    filter(
        weight == 'raw',
        metric == 'cis',
        chr == 'genome.wide',
        ReadFilter == 'mapq_30',
        bins.pct.covered >= 0.80
    ) %>% 
    group_by(Sample.ID) %>% 
    slice_min(resolution, n=1) %>% 
    ungroup() %>% 
    select(
        -c(
            weight,
            metric,
            chr
        )
    ) %>%
    mutate(ReadFilter=as.integer(str_remove(ReadFilter, 'mapq_'))) %>% 
    pivot_longer(
        c(starts_with('bins'), resolution, ReadFilter),
        names_to='metric',
        values_to='n'
    ) %>%
    mutate(
        metric=
            case_when(
                metric == 'bins.n.nz'        ~ NA,
                metric == 'bins.n.covered'   ~ 'Bins >= 1K Contacts',
                metric == 'bins.n.total'     ~ NA,
                metric == 'bins.pct.nz'      ~ NA,
                metric == 'bins.pct.covered' ~ '% Bins >= 1K Contacts',
                metric == 'resolution'       ~ 'Minimum Viable Resolution',
                metric == 'min_mapq'         ~ 'Minimum MAPQ',
                TRUE ~ NA
            )
    ) %>% 
    filter(!is.na(metric)) %>% 
    # Add stats per matrix
    bind_rows(
        pair.stats.list$general.stats %>%
        select(
            Sample.ID,
            stat,
            value
        ) %>%
        rename(
            'metric'=stat,
            'n'=value
        )
    ) %>% 
    # add pair categories
    bind_rows(
        pair.plot.df %>%
        select(
            Sample.ID,
            Category,
            value
        ) %>%
        rename(
            'metric'=Category,
            'n'=value
        ) %>%
        mutate(metric=paste0('pairs.', metric))
    ) %>% 
    pivot_wider(
        names_from=metric,
        values_from=n
    )
}

make_pair_qc_df <- function(
    pair.stats.list,
    ...){
    pair.stats.list$general.stats %>% 
    select(-c(category)) %>% 
    filter(stat %in% c('trans', 'cis')) %>% 
    dplyr::rename('interaction'=stat) %>% 
    add_column(range.start=0) %>% 
    bind_rows(pair.stats.list$distance.stats) %>% 
    mutate(
        range.end=ifelse(is.na(range.end), Inf, range.end),
        Category=
            case_when(
                orientation =='-+'   & range.end < 1001    ~ 'self-circle', 
                orientation =='+-'   & range.end < 1001    ~ 'dangling-end', 
                range.start >= 20000                       ~ 'Long.Range  >  20Kb',
                range.start >=  1000 & range.start < 20001 ~ 'Short.Range <= 20Kb',
                range.end   <=  1000                       ~ 'Too.Short   <=  1Kb',
                interaction == 'cis' & range.end == Inf    ~ 'Cis.Total',
                interaction == 'trans'                     ~ 'Trans',
            )
    ) %>%
    mutate(
        Category=
            factor(
                Category,
                levels=
                    c(
                        'self-circle', 
                        'dangling-end', 
                        'Too.Short   <=  1Kb',
                        'Short.Range <= 20Kb',
                        'Long.Range  >  20Kb',
                        'Cis.Total',
                        'Trans'
                    )
            )
    ) %>% 
    group_by(Sample.ID, Category) %>% 
    summarize(
        value=sum(value),
        # total per sample
        total.unique.contacts=unique(total.unique.contacts)
    ) %>% 
    ungroup() %>% 
    mutate(frac=100 * (value / total.unique.contacts))
}
###############
# Plot Matrix QC stuff
plot_qc_barplot <- function(
    plot.df,
    y_val,
    facet_row,
    facet_col,
    yintercept=35,
    ...){
    plot.df %>%
    ggplot(
        aes(
            x=Category,
            y=.data[[y_val]],
            fill=Sample.ID
        )
    ) +
    geom_col(position = "dodge") +
    geom_hline(yintercept=yintercept, color='black', linetype='dashed') +
    # scale_y_continuous(breaks=~ seq(.x, .y, 5)) +
    scale_y_continuous(
        breaks=seq(0, max(plot.df[[y_val]]), 5),
        expand=c(0, 0)
    ) +
    facet_grid2(
        rows=vars(!!sym(facet_row)),
        cols=vars(!!sym(facet_col)),
        scales='fixed'
    ) +
    labs(y=y_val) +
    theme(
        ...,
        axis.title.x=element_blank(),
        axis.text.x=
            element_text(
                hjust=1,
                angle=35
            )
    ) + 
    add_ggtheme()
}

plot_pair.orientation_lineplot <- function(
    plot.df,
    facet_row,
    ...){
    plot.df %>% 
    ggplot(
        aes(
            x=range.start,
            y=value,
        )
    ) + 
    # geom_line(aes(linetype=orientation, color=Sample.ID)) +
    geom_line(aes(color=orientation)) +
    # geom_text(aes(label=Sample.ID), x=1.5, y=1.8) +
    scale_x_log10(labels=label_log()) +
    scale_y_log10(labels=label_log()) +
    # facet_wrap( ~ Sample.ID, ncol=3) +
    facet_grid(
        rows=vars(!!sym(facet_row)),
        scales='fixed'
    ) +
    labs(
        x='Pair Distance',
        y='Raw Contacts'
    ) +
    theme(
        # legend.position='right'
        legend.position='inside',
        legend.position.inside=c(0.95, 0.95), # c(0,0) bottom left, c(1,1) top-right.
        # legend.background=
        #     element_rect(
        #         fill="white",
        #         colour=NA
        #     )
    ) +
    add_ggtheme()
}

plot_cistrans_chromosome_heatmap <- function(
    plot.df,
    fill_var,
    ...){
    plot.df %>%
    ggplot(
        aes(
            x=chr1,
            y=chr2
        )
    ) +
    geom_tile(
        aes(
            fill=.data[[fill_var]]
        )
    ) +
    scale_fill_gradient(
        low='grey90',
        high='red'
    ) +
    facet_wrap(~ Sample.ID) +
    theme(
        legend.position='top',
        axis.text.x=element_text(angle=45, hjust=1)
    ) +
    add_ggtheme()
}
