# Copied from here:
# https://www.codegenes.net/blog/automatic-toc-in-github-flavoured-markdown/#option-1-github-actions-automated-on-push
name: Generate TOC
on: push
name: DSL TOC Action
jobs:
  doDOCTOC:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Call DOCTOC_action"
        uses: DougLeonard/DOCTOC_action@v1      

